### ISSUE TITLE
Local LORA adapter fails

### ISSUE THREAD

**Issue by mwilmes** [mzbac/flux.swift.cli#3]
Seemingly it tries to find the adapter on HF first instead of just loading it from local file (Nightly Build 2024-10-16):

```
% ls vanGogh.safetensors 
vanGogh.safetensors

% ./flux --prompt "A portrait in the style of Van Gogh" --lora-path vanGogh.safetensors --output vangogh_portrait.png 
Error: authorizationRequired

% ./flux --prompt "A portrait in the style of Van Gogh" --lora-path /Users/me/flux/vanGogh.safetensors --output vangogh_portrait.png
Error: authorizationRequired

% ./flux --model dev --prompt "A portrait in the style of Van Gogh" --lora-path ./vanGogh.safetensors --output vangogh_portrait.png 
Hugging Face token is not provided. Using default token from /Users/me/.cache/huggingface/token
Error: authorizationRequired
```

Regardless of full path or just filename it does not want to pick up the local file.

**Comment by mwilmes** [comment]
Got it. Was using the nightly build. Latest regular release is fine.

**Comment by mzbac** [comment]
Thanks for bringing this up, @mwilmes! The Nightly Build can sometimes include changes haven't been fully tested, and it seems that was the case here. The issue should have been fixed in the latest Nightly Build.
